-- SDKWork memory consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_memory_baseline.sql
-- Generated from canonical application-root migrations.
-- Do not edit this folded baseline directly; run `pnpm db:materialize:baseline`.

-- source: database/migrations/postgres/0001_memory_schema.up.sql
CREATE TABLE IF NOT EXISTS ai_space (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  organization_id BIGINT NOT NULL DEFAULT 0,
  owner_subject_type VARCHAR(32) NOT NULL,
  owner_subject_id VARCHAR(128) NOT NULL,
  space_type VARCHAR(32) NOT NULL,
  display_name VARCHAR(200) NOT NULL,
  default_scope VARCHAR(32) NOT NULL,
  lifecycle_status VARCHAR(32) NOT NULL,
  metadata_json TEXT,
  policy_json TEXT,
  created_by BIGINT,
  updated_by BIGINT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  deleted_at TEXT,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_space_uuid
  ON ai_space (tenant_id, uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_space_owner_type
  ON ai_space (tenant_id, owner_subject_type, owner_subject_id, space_type);

CREATE TABLE IF NOT EXISTS ai_event (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT NOT NULL REFERENCES ai_space(id),
  user_id BIGINT,
  actor_type VARCHAR(32) NOT NULL,
  actor_id VARCHAR(128),
  session_id VARCHAR(128),
  trace_id VARCHAR(128),
  request_id VARCHAR(64),
  idempotency_key VARCHAR(128),
  event_type VARCHAR(64) NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  source_ref VARCHAR(256),
  event_time TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  payload_hash VARCHAR(128) NOT NULL,
  sensitivity_level VARCHAR(32) NOT NULL,
  ingestion_status VARCHAR(32) NOT NULL,
  created_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_event_uuid
  ON ai_event (tenant_id, uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_event_idempotency
  ON ai_event (tenant_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS ai_record (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT NOT NULL REFERENCES ai_space(id),
  user_id BIGINT,
  scope VARCHAR(32) NOT NULL,
  memory_type VARCHAR(32) NOT NULL,
  subject VARCHAR(256),
  predicate VARCHAR(128),
  object_text TEXT NOT NULL,
  canonical_text TEXT NOT NULL,
  summary_text TEXT,
  language VARCHAR(16),
  confidence DOUBLE PRECISION NOT NULL,
  evidence_count INTEGER NOT NULL DEFAULT 0,
  contradiction_count INTEGER NOT NULL DEFAULT 0,
  importance_score DOUBLE PRECISION NOT NULL,
  recency_score DOUBLE PRECISION NOT NULL,
  habit_strength DOUBLE PRECISION,
  valid_from TEXT,
  valid_to TEXT,
  expires_at TEXT,
  status VARCHAR(32) NOT NULL,
  sensitivity_level VARCHAR(32) NOT NULL,
  metadata_json TEXT,
  tags_json TEXT,
  supersedes_memory_id BIGINT REFERENCES ai_record(id),
  superseded_by_memory_id BIGINT REFERENCES ai_record(id),
  created_by BIGINT,
  updated_by BIGINT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  deleted_at TEXT,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_record_uuid
  ON ai_record (tenant_id, uuid);

CREATE INDEX IF NOT EXISTS idx_ai_record_scope_type_status
  ON ai_record (tenant_id, space_id, scope, memory_type, status, updated_at);

CREATE TABLE IF NOT EXISTS ai_record_source (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  memory_id BIGINT NOT NULL REFERENCES ai_record(id),
  event_id BIGINT NOT NULL REFERENCES ai_event(id),
  source_role VARCHAR(32) NOT NULL,
  confidence_delta DOUBLE PRECISION,
  created_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_record_source_pair
  ON ai_record_source (tenant_id, memory_id, event_id, source_role);

CREATE TABLE IF NOT EXISTS ai_candidate (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT NOT NULL REFERENCES ai_space(id),
  user_id BIGINT,
  candidate_type VARCHAR(32) NOT NULL,
  memory_type VARCHAR(32) NOT NULL,
  proposed_text TEXT NOT NULL,
  proposed_payload_json TEXT,
  target_memory_id BIGINT REFERENCES ai_record(id),
  evidence_json TEXT,
  confidence DOUBLE PRECISION NOT NULL,
  novelty_score DOUBLE PRECISION,
  risk_score DOUBLE PRECISION,
  decision_state VARCHAR(32) NOT NULL,
  decision_reason VARCHAR(256),
  decided_by BIGINT,
  decided_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_candidate_uuid
  ON ai_candidate (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS ai_habit (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT NOT NULL REFERENCES ai_space(id),
  user_id BIGINT NOT NULL,
  habit_key VARCHAR(160) NOT NULL,
  habit_type VARCHAR(64) NOT NULL,
  description TEXT NOT NULL,
  stage VARCHAR(32) NOT NULL,
  strength DOUBLE PRECISION NOT NULL,
  confidence DOUBLE PRECISION NOT NULL,
  support_count INTEGER NOT NULL DEFAULT 0,
  last_signal_at TEXT,
  promoted_memory_id BIGINT REFERENCES ai_record(id),
  decay_after TEXT,
  metadata_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_habit_key
  ON ai_habit (tenant_id, space_id, user_id, habit_key);

CREATE TABLE IF NOT EXISTS ai_retrieval_trace (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT,
  retrieval_profile_id BIGINT,
  actor_id VARCHAR(128),
  query_text TEXT,
  query_hash VARCHAR(128) NOT NULL,
  retrievers_json TEXT,
  latency_ms INTEGER,
  result_count INTEGER NOT NULL DEFAULT 0,
  degraded BOOLEAN NOT NULL DEFAULT FALSE,
  metadata_json TEXT,
  created_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_retrieval_trace_uuid
  ON ai_retrieval_trace (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS ai_retrieval_hit (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  retrieval_trace_id BIGINT NOT NULL REFERENCES ai_retrieval_trace(id),
  memory_id BIGINT REFERENCES ai_record(id),
  retriever_name VARCHAR(64) NOT NULL,
  result_rank INTEGER NOT NULL,
  raw_score DOUBLE PRECISION,
  fused_score DOUBLE PRECISION,
  explanation_json TEXT,
  status VARCHAR(32) NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ai_retrieval_hit_trace_rank
  ON ai_retrieval_hit (tenant_id, retrieval_trace_id, result_rank);

CREATE TABLE IF NOT EXISTS ai_context_pack (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  retrieval_trace_id BIGINT REFERENCES ai_retrieval_trace(id),
  actor_id VARCHAR(128),
  query_text TEXT,
  pack_json TEXT NOT NULL,
  estimated_tokens INTEGER NOT NULL,
  truncated BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_context_pack_uuid
  ON ai_context_pack (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS ai_index (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT,
  index_kind VARCHAR(32) NOT NULL,
  implementation_profile_id BIGINT,
  provider_binding_id BIGINT,
  schema_version VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  rebuild_cursor VARCHAR(256),
  config_json TEXT,
  last_rebuilt_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_index_uuid
  ON ai_index (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS ai_retrieval_profile (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT,
  name VARCHAR(160) NOT NULL,
  strategy VARCHAR(64) NOT NULL,
  retrievers_json TEXT NOT NULL,
  fusion_policy_json TEXT,
  rerank_policy_json TEXT,
  top_k INTEGER NOT NULL,
  context_budget_tokens INTEGER NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_retrieval_profile_uuid
  ON ai_retrieval_profile (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS ai_implementation_profile (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  name VARCHAR(160) NOT NULL,
  implementation_kind VARCHAR(64) NOT NULL,
  role VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  capability_json TEXT NOT NULL,
  config_json TEXT,
  rollout_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_implementation_profile_uuid
  ON ai_implementation_profile (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS ai_provider_binding (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  provider_kind VARCHAR(32) NOT NULL,
  provider_code VARCHAR(128) NOT NULL,
  display_name VARCHAR(160) NOT NULL,
  endpoint_ref VARCHAR(256),
  secret_ref VARCHAR(256),
  model_ref VARCHAR(256),
  capabilities_json TEXT NOT NULL,
  config_json TEXT,
  health_state VARCHAR(32) NOT NULL,
  last_health_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_provider_binding_uuid
  ON ai_provider_binding (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS ai_eval_run (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  eval_type VARCHAR(64) NOT NULL,
  state VARCHAR(32) NOT NULL,
  metrics_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_eval_run_uuid
  ON ai_eval_run (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS ai_audit_log (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  actor_type VARCHAR(32) NOT NULL,
  actor_id VARCHAR(128),
  action VARCHAR(128) NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  resource_id VARCHAR(128),
  request_id VARCHAR(64),
  trace_id VARCHAR(128),
  result VARCHAR(32) NOT NULL,
  reason VARCHAR(256),
  metadata_json TEXT,
  created_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_audit_log_uuid
  ON ai_audit_log (tenant_id, uuid);

CREATE TABLE IF NOT EXISTS ai_outbox_event (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  aggregate_type VARCHAR(64) NOT NULL,
  aggregate_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  event_version VARCHAR(32) NOT NULL,
  payload_json TEXT NOT NULL,
  publish_state VARCHAR(32) NOT NULL,
  published_at TEXT,
  retry_count INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_outbox_event_uuid
  ON ai_outbox_event (tenant_id, uuid);

-- source: database/migrations/postgres/0002_memory_indexes.up.sql
-- Phase-1 secondary indexes materialized from docs/schema-registry (DATABASE_SPEC alignment).

CREATE INDEX IF NOT EXISTS idx_ai_space_tenant_status
  ON ai_space (tenant_id, lifecycle_status, updated_at);

CREATE INDEX IF NOT EXISTS idx_ai_event_space_time
  ON ai_event (tenant_id, space_id, event_time, id);

CREATE INDEX IF NOT EXISTS idx_ai_event_session_time
  ON ai_event (tenant_id, session_id, event_time);

CREATE INDEX IF NOT EXISTS idx_ai_event_type_time
  ON ai_event (tenant_id, event_type, event_time);

CREATE INDEX IF NOT EXISTS idx_ai_event_hash
  ON ai_event (tenant_id, payload_hash);

CREATE INDEX IF NOT EXISTS idx_ai_record_user_type
  ON ai_record (tenant_id, user_id, memory_type, status, updated_at);

CREATE INDEX IF NOT EXISTS idx_ai_record_subject_predicate
  ON ai_record (tenant_id, space_id, subject, predicate, status);

CREATE INDEX IF NOT EXISTS idx_ai_record_validity
  ON ai_record (tenant_id, valid_from, valid_to, expires_at);

CREATE INDEX IF NOT EXISTS idx_ai_record_supersession
  ON ai_record (tenant_id, supersedes_memory_id, superseded_by_memory_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_record_source_uuid
  ON ai_record_source (tenant_id, uuid);

CREATE INDEX IF NOT EXISTS idx_ai_record_source_event
  ON ai_record_source (tenant_id, event_id);

CREATE INDEX IF NOT EXISTS idx_ai_candidate_state
  ON ai_candidate (tenant_id, space_id, decision_state, updated_at);

CREATE INDEX IF NOT EXISTS idx_ai_candidate_target
  ON ai_candidate (tenant_id, target_memory_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_habit_uuid
  ON ai_habit (tenant_id, uuid);

CREATE INDEX IF NOT EXISTS idx_ai_habit_stage
  ON ai_habit (tenant_id, space_id, stage, confidence, updated_at);

CREATE INDEX IF NOT EXISTS idx_ai_retrieval_trace_profile_created
  ON ai_retrieval_trace (tenant_id, retrieval_profile_id, created_at);

CREATE INDEX IF NOT EXISTS idx_ai_retrieval_trace_actor_created
  ON ai_retrieval_trace (tenant_id, actor_id, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_retrieval_hit_uuid
  ON ai_retrieval_hit (tenant_id, uuid);

CREATE INDEX IF NOT EXISTS idx_ai_retrieval_hit_memory
  ON ai_retrieval_hit (tenant_id, memory_id, status);

CREATE INDEX IF NOT EXISTS idx_ai_context_pack_trace
  ON ai_context_pack (tenant_id, retrieval_trace_id);

CREATE INDEX IF NOT EXISTS idx_ai_context_pack_actor_created
  ON ai_context_pack (tenant_id, actor_id, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_index_kind_space
  ON ai_index (tenant_id, space_id, index_kind, schema_version);

CREATE INDEX IF NOT EXISTS idx_ai_index_status
  ON ai_index (tenant_id, space_id, index_kind, status);

CREATE INDEX IF NOT EXISTS idx_ai_retrieval_profile_scope
  ON ai_retrieval_profile (tenant_id, space_id, status, updated_at);

CREATE INDEX IF NOT EXISTS idx_ai_implementation_profile_kind
  ON ai_implementation_profile (tenant_id, implementation_kind, status);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_provider_binding_code
  ON ai_provider_binding (tenant_id, provider_kind, provider_code);

CREATE INDEX IF NOT EXISTS idx_ai_provider_binding_health
  ON ai_provider_binding (tenant_id, provider_kind, health_state, updated_at);

CREATE INDEX IF NOT EXISTS idx_ai_eval_run_type_state
  ON ai_eval_run (tenant_id, eval_type, state, created_at);

CREATE INDEX IF NOT EXISTS idx_ai_audit_actor_time
  ON ai_audit_log (tenant_id, actor_type, actor_id, created_at);

CREATE INDEX IF NOT EXISTS idx_ai_audit_resource_time
  ON ai_audit_log (tenant_id, resource_type, resource_id, created_at);

CREATE INDEX IF NOT EXISTS idx_ai_audit_action_time
  ON ai_audit_log (tenant_id, action, created_at);

CREATE INDEX IF NOT EXISTS idx_ai_outbox_state
  ON ai_outbox_event (tenant_id, publish_state, created_at);

-- source: database/migrations/postgres/0003_memory_tenant_preference.up.sql
-- Tenant-level and user-level preference store (schema-registry 005-memory-governance.yaml).

CREATE TABLE IF NOT EXISTS ai_tenant_preference (
  id BIGINT NOT NULL PRIMARY KEY,
  tenant_id BIGINT NOT NULL,
  user_id BIGINT,
  preference_key TEXT NOT NULL,
  preference_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

-- NULLS NOT DISTINCT ensures tenant-level preferences (user_id IS NULL) remain unique
-- per (tenant_id, preference_key). Requires PostgreSQL 15+.
CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_tenant_preference_scope
  ON ai_tenant_preference (tenant_id, user_id, preference_key)
  NULLS NOT DISTINCT;

-- source: database/migrations/postgres/0004_memory_learning_job.up.sql
-- Async learning/governance job queue (schema-registry 002-memory-learning.yaml).

CREATE TABLE IF NOT EXISTS ai_learning_job (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT REFERENCES ai_space(id),
  job_type VARCHAR(64) NOT NULL,
  state VARCHAR(32) NOT NULL,
  priority INT NOT NULL DEFAULT 0,
  idempotency_key VARCHAR(128),
  input_json TEXT,
  result_json TEXT,
  error_json TEXT,
  started_at TEXT,
  finished_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_learning_job_uuid
  ON ai_learning_job (tenant_id, uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_learning_job_idempotency
  ON ai_learning_job (tenant_id, job_type, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ai_learning_job_state
  ON ai_learning_job (tenant_id, job_type, state, priority DESC, created_at ASC);

-- source: database/migrations/postgres/0005_memory_record_fulltext_search.up.sql
-- PostgreSQL full-text search for ai_record (DATABASE_SPEC / architecture design alignment).

ALTER TABLE ai_record ADD COLUMN IF NOT EXISTS search_document TSVECTOR;

CREATE INDEX IF NOT EXISTS idx_ai_record_search_document
  ON ai_record USING GIN (search_document);

UPDATE ai_record
SET search_document = to_tsvector(
  'simple',
  coalesce(canonical_text, '') || ' ' ||
  coalesce(object_text, '') || ' ' ||
  coalesce(subject, '') || ' ' ||
  coalesce(predicate, '')
)
WHERE search_document IS NULL
  AND status <> 'deleted';

CREATE OR REPLACE FUNCTION ai_record_search_document_trigger() RETURNS trigger AS $$
BEGIN
  NEW.search_document := to_tsvector(
    'simple',
    coalesce(NEW.canonical_text, '') || ' ' ||
    coalesce(NEW.object_text, '') || ' ' ||
    coalesce(NEW.subject, '') || ' ' ||
    coalesce(NEW.predicate, '')
  );
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ai_record_search_document ON ai_record;
CREATE TRIGGER trg_ai_record_search_document
  BEFORE INSERT OR UPDATE OF canonical_text, object_text, subject, predicate, status
  ON ai_record
  FOR EACH ROW
  WHEN (NEW.status <> 'deleted')
  EXECUTE FUNCTION ai_record_search_document_trigger();

-- source: database/migrations/postgres/0006_memory_eval_run_extend.up.sql
-- Extend ai_eval_run to align with schema-registry 005-memory-governance.yaml.
-- Adds dataset_ref, profile_ref, result_json, started_at, finished_at columns
-- declared in the design contract but absent from 0001_memory_phase1.

ALTER TABLE ai_eval_run ADD COLUMN IF NOT EXISTS dataset_ref VARCHAR(256);
ALTER TABLE ai_eval_run ADD COLUMN IF NOT EXISTS profile_ref VARCHAR(256);
ALTER TABLE ai_eval_run ADD COLUMN IF NOT EXISTS result_json TEXT;
ALTER TABLE ai_eval_run ADD COLUMN IF NOT EXISTS started_at TEXT;
ALTER TABLE ai_eval_run ADD COLUMN IF NOT EXISTS finished_at TEXT;

-- source: database/migrations/postgres/0007_memory_commercial_management.up.sql
-- Commercial memory management tables.
-- Activates planned tables (ai_entity, ai_edge, ai_policy) and adds the
-- commercial management layer (ai_subject, ai_memory_binding,
-- ai_capability_binding, ai_policy_assignment, ai_relation_rebuild_job,
-- ai_commercial_readiness_snapshot) per schema-registry 006-memory-commercial-management.yaml.

-- Activate ai_entity (previously planned in 001-memory-core.yaml).
CREATE TABLE IF NOT EXISTS ai_entity (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT NOT NULL REFERENCES ai_space(id),
  entity_type VARCHAR(64) NOT NULL,
  canonical_name VARCHAR(256) NOT NULL,
  aliases_json TEXT,
  attributes_json TEXT,
  sensitivity_level VARCHAR(32) NOT NULL DEFAULT 'internal',
  status VARCHAR(32) NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_entity_uuid
  ON ai_entity (tenant_id, uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_entity_name
  ON ai_entity (tenant_id, space_id, entity_type, canonical_name);

CREATE INDEX IF NOT EXISTS idx_ai_entity_type_status
  ON ai_entity (tenant_id, space_id, entity_type, status);

-- Activate ai_edge (previously planned in 001-memory-core.yaml).
CREATE TABLE IF NOT EXISTS ai_edge (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT NOT NULL REFERENCES ai_space(id),
  source_entity_id BIGINT NOT NULL REFERENCES ai_entity(id),
  target_entity_id BIGINT NOT NULL REFERENCES ai_entity(id),
  relation_type VARCHAR(64) NOT NULL,
  weight DOUBLE PRECISION,
  source_memory_id BIGINT REFERENCES ai_record(id),
  valid_from TEXT,
  valid_to TEXT,
  status VARCHAR(32) NOT NULL,
  metadata_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_edge_uuid
  ON ai_edge (tenant_id, uuid);

CREATE INDEX IF NOT EXISTS idx_ai_edge_source
  ON ai_edge (tenant_id, space_id, source_entity_id, relation_type, status);

CREATE INDEX IF NOT EXISTS idx_ai_edge_target
  ON ai_edge (tenant_id, space_id, target_entity_id, relation_type, status);

CREATE INDEX IF NOT EXISTS idx_ai_edge_validity
  ON ai_edge (tenant_id, valid_from, valid_to);

-- Activate ai_policy (previously planned in 004-memory-provider.yaml).
CREATE TABLE IF NOT EXISTS ai_policy (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  policy_type VARCHAR(64) NOT NULL,
  scope VARCHAR(32) NOT NULL,
  scope_ref VARCHAR(128),
  status VARCHAR(32) NOT NULL,
  policy_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_policy_uuid
  ON ai_policy (tenant_id, uuid);

CREATE INDEX IF NOT EXISTS idx_ai_policy_type_scope
  ON ai_policy (tenant_id, policy_type, scope, status);

-- Commercial management: subject projections.
CREATE TABLE IF NOT EXISTS ai_subject (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  organization_id BIGINT NOT NULL DEFAULT 0,
  subject_type VARCHAR(32) NOT NULL,
  subject_ref VARCHAR(128) NOT NULL,
  display_name VARCHAR(200) NOT NULL,
  default_space_id BIGINT REFERENCES ai_space(id),
  status VARCHAR(32) NOT NULL,
  metadata_json TEXT,
  created_by BIGINT,
  updated_by BIGINT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  deleted_at TEXT,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_subject_uuid
  ON ai_subject (tenant_id, uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_subject_ref
  ON ai_subject (tenant_id, subject_type, subject_ref);

CREATE INDEX IF NOT EXISTS idx_ai_subject_status
  ON ai_subject (tenant_id, subject_type, status, updated_at);

CREATE INDEX IF NOT EXISTS idx_ai_subject_space
  ON ai_subject (tenant_id, default_space_id, status);

-- Commercial management: auditable memory bindings.
CREATE TABLE IF NOT EXISTS ai_memory_binding (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  space_id BIGINT REFERENCES ai_space(id),
  binding_kind VARCHAR(32) NOT NULL,
  source_subject_id BIGINT REFERENCES ai_subject(id),
  source_entity_id BIGINT REFERENCES ai_entity(id),
  source_memory_id BIGINT REFERENCES ai_record(id),
  source_external_ref_type VARCHAR(64),
  source_external_ref_id VARCHAR(128),
  source_external_ref_source VARCHAR(64),
  target_subject_id BIGINT REFERENCES ai_subject(id),
  target_entity_id BIGINT REFERENCES ai_entity(id),
  target_memory_id BIGINT REFERENCES ai_record(id),
  target_space_id BIGINT REFERENCES ai_space(id),
  target_external_ref_type VARCHAR(64),
  target_external_ref_id VARCHAR(128),
  target_external_ref_source VARCHAR(64),
  binding_role VARCHAR(32) NOT NULL,
  capability_codes_json TEXT,
  retrieval_profile_id BIGINT REFERENCES ai_retrieval_profile(id),
  policy_assignment_id BIGINT,
  strength DOUBLE PRECISION,
  valid_from TEXT,
  valid_to TEXT,
  status VARCHAR(32) NOT NULL,
  metadata_json TEXT,
  created_by BIGINT,
  updated_by BIGINT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  deleted_at TEXT,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_memory_binding_uuid
  ON ai_memory_binding (tenant_id, uuid);

CREATE INDEX IF NOT EXISTS idx_ai_binding_source_subject
  ON ai_memory_binding (tenant_id, source_subject_id, binding_kind, status);

CREATE INDEX IF NOT EXISTS idx_ai_binding_source_entity
  ON ai_memory_binding (tenant_id, source_entity_id, binding_kind, status);

CREATE INDEX IF NOT EXISTS idx_ai_binding_target_memory
  ON ai_memory_binding (tenant_id, target_memory_id, binding_kind, status);

CREATE INDEX IF NOT EXISTS idx_ai_binding_target_space
  ON ai_memory_binding (tenant_id, target_space_id, binding_kind, status);

CREATE INDEX IF NOT EXISTS idx_ai_binding_external_source
  ON ai_memory_binding (tenant_id, source_external_ref_source, source_external_ref_type, source_external_ref_id);

CREATE INDEX IF NOT EXISTS idx_ai_binding_validity
  ON ai_memory_binding (tenant_id, valid_from, valid_to, status);

-- Commercial management: capability bindings.
CREATE TABLE IF NOT EXISTS ai_capability_binding (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  capability_code VARCHAR(32) NOT NULL,
  target_type VARCHAR(32) NOT NULL,
  target_id BIGINT NOT NULL,
  mode VARCHAR(32) NOT NULL,
  priority INTEGER NOT NULL DEFAULT 0,
  retrieval_profile_id BIGINT REFERENCES ai_retrieval_profile(id),
  implementation_profile_id BIGINT REFERENCES ai_implementation_profile(id),
  policy_assignment_id BIGINT,
  status VARCHAR(32) NOT NULL,
  valid_from TEXT,
  valid_to TEXT,
  metadata_json TEXT,
  created_by BIGINT,
  updated_by BIGINT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  deleted_at TEXT,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_capability_binding_uuid
  ON ai_capability_binding (tenant_id, uuid);

CREATE INDEX IF NOT EXISTS idx_ai_capability_target
  ON ai_capability_binding (tenant_id, target_type, target_id, capability_code, status);

CREATE INDEX IF NOT EXISTS idx_ai_capability_priority
  ON ai_capability_binding (tenant_id, capability_code, mode, priority);

CREATE INDEX IF NOT EXISTS idx_ai_capability_validity
  ON ai_capability_binding (tenant_id, valid_from, valid_to, status);

-- Commercial management: policy assignments.
CREATE TABLE IF NOT EXISTS ai_policy_assignment (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  policy_id BIGINT NOT NULL REFERENCES ai_policy(id),
  target_type VARCHAR(32) NOT NULL,
  target_id BIGINT NOT NULL,
  priority INTEGER NOT NULL DEFAULT 0,
  inheritance_mode VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  valid_from TEXT,
  valid_to TEXT,
  created_by BIGINT,
  updated_by BIGINT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  deleted_at TEXT,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_policy_assignment_uuid
  ON ai_policy_assignment (tenant_id, uuid);

CREATE INDEX IF NOT EXISTS idx_ai_policy_assignment_target
  ON ai_policy_assignment (tenant_id, target_type, target_id, status, priority);

CREATE INDEX IF NOT EXISTS idx_ai_policy_assignment_policy
  ON ai_policy_assignment (tenant_id, policy_id, status);

CREATE INDEX IF NOT EXISTS idx_ai_policy_assignment_validity
  ON ai_policy_assignment (tenant_id, valid_from, valid_to, status);

-- Commercial management: relation rebuild jobs.
CREATE TABLE IF NOT EXISTS ai_relation_rebuild_job (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  job_type VARCHAR(64) NOT NULL,
  state VARCHAR(32) NOT NULL,
  scope_type VARCHAR(32) NOT NULL,
  scope_id VARCHAR(128),
  idempotency_key VARCHAR(128),
  input_json TEXT,
  result_json TEXT,
  error_json TEXT,
  started_at TEXT,
  finished_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_relation_rebuild_job_uuid
  ON ai_relation_rebuild_job (tenant_id, uuid);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_relation_rebuild_job_idempotency
  ON ai_relation_rebuild_job (tenant_id, idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ai_relation_rebuild_job_state
  ON ai_relation_rebuild_job (tenant_id, state, created_at);

CREATE INDEX IF NOT EXISTS idx_ai_relation_rebuild_job_scope
  ON ai_relation_rebuild_job (tenant_id, scope_type, scope_id, state);

-- Commercial management: commercial readiness snapshot (read model).
CREATE TABLE IF NOT EXISTS ai_commercial_readiness_snapshot (
  id BIGINT PRIMARY KEY,
  uuid VARCHAR(64) NOT NULL,
  tenant_id BIGINT NOT NULL,
  implementation_profile_id BIGINT REFERENCES ai_implementation_profile(id),
  score DOUBLE PRECISION NOT NULL,
  state VARCHAR(32) NOT NULL,
  contract_coverage_json TEXT,
  management_coverage_json TEXT,
  runtime_conformance_json TEXT,
  privacy_coverage_json TEXT,
  audit_coverage_json TEXT,
  sdk_coverage_json TEXT,
  evaluation_coverage_json TEXT,
  observability_coverage_json TEXT,
  migration_coverage_json TEXT,
  blocking_findings_json TEXT,
  warning_findings_json TEXT,
  created_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_ai_commercial_readiness_uuid
  ON ai_commercial_readiness_snapshot (tenant_id, uuid);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_commercial_readiness_tenant
  ON ai_commercial_readiness_snapshot (tenant_id, implementation_profile_id);

-- source: database/migrations/postgres/0008_memory_outbox_delivery_lease.up.sql
ALTER TABLE ai_outbox_event
  ADD COLUMN IF NOT EXISTS lease_owner VARCHAR(128),
  ADD COLUMN IF NOT EXISTS lease_token VARCHAR(128),
  ADD COLUMN IF NOT EXISTS lease_expires_at TEXT,
  ADD COLUMN IF NOT EXISTS next_attempt_at TEXT;

CREATE INDEX IF NOT EXISTS idx_ai_outbox_event_delivery_lease
  ON ai_outbox_event (publish_state, next_attempt_at, lease_expires_at, id);

-- source: database/migrations/postgres/0009_memory_job_execution_lease.up.sql
ALTER TABLE ai_learning_job
  ADD COLUMN IF NOT EXISTS lease_owner VARCHAR(128),
  ADD COLUMN IF NOT EXISTS lease_token VARCHAR(128),
  ADD COLUMN IF NOT EXISTS lease_expires_at TEXT;

ALTER TABLE ai_eval_run
  ADD COLUMN IF NOT EXISTS lease_owner VARCHAR(128),
  ADD COLUMN IF NOT EXISTS lease_token VARCHAR(128),
  ADD COLUMN IF NOT EXISTS lease_expires_at TEXT;

CREATE INDEX IF NOT EXISTS idx_ai_learning_job_execution_lease
  ON ai_learning_job (state, lease_expires_at, priority, id);
CREATE INDEX IF NOT EXISTS idx_ai_eval_run_execution_lease
  ON ai_eval_run (state, lease_expires_at, id);
